# Generated by Django 4.2.17 on 2026-08-04 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0008_room_room_uq_room_property_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('occupied', 'Occupied'), ('blocked', 'Blocked'), ('maintenance', 'Maintenance'), ('out_of_order', 'Out of Order')], default='available', max_length=30)),
                ('is_available', models.BooleanField(default=True)),
                ('inventory_count', models.PositiveIntegerField(default=1)),
                ('available_count', models.PositiveIntegerField(default=1)),
                ('minimum_stay', models.PositiveSmallIntegerField(default=1)),
                ('maximum_stay', models.PositiveSmallIntegerField(default=30)),
                ('closed_to_arrival', models.BooleanField(default=False)),
                ('closed_to_departure', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_calendar', to='booking.room')),
            ],
            options={
                'ordering': ['date', 'room'],
                'indexes': [models.Index(fields=['room', 'date'], name='idx_inventory_room_date'), models.Index(fields=['date', 'status'], name='idx_inventory_date_status'), models.Index(fields=['status', 'is_available'], name='idx_inventory_status_available')],
            },
        ),
        migrations.AddConstraint(
            model_name='inventorycalendar',
            constraint=models.UniqueConstraint(fields=('room', 'date'), name='uq_inventory_calendar_room_date'),
        ),
    ]
