# Generated by Django 4.2.17 on 2026-08-04 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_room_room_uq_room_property_number_and_more'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block_type', models.CharField(choices=[('maintenance', 'Maintenance'), ('owner_stay', 'Owner Stay'), ('vip_hold', 'VIP Hold'), ('group_hold', 'Group Hold'), ('housekeeping', 'Housekeeping'), ('renovation', 'Renovation'), ('emergency', 'Emergency'), ('other', 'Other')], max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='active', max_length=20)),
                ('blocks_arrival', models.BooleanField(default=True)),
                ('blocks_departure', models.BooleanField(default=True)),
                ('blocks_inventory', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_blocks', to='booking.room')),
            ],
            options={
                'ordering': ['-start_date', 'room'],
                'indexes': [models.Index(fields=['room', 'start_date'], name='idx_block_room_start'), models.Index(fields=['start_date', 'end_date'], name='idx_block_dates'), models.Index(fields=['status', 'block_type'], name='idx_block_status_type')],
            },
        ),
    ]
