# Generated by Django 4.2.30 on 2026-08-04 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0002_inventoryblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adjustment_type', models.CharField(choices=[('manual', 'Manual'), ('booking', 'Booking'), ('ota_sync', 'OTA Sync'), ('housekeeping', 'Housekeeping'), ('maintenance', 'Maintenance'), ('ai', 'AI Recommendation'), ('system', 'System'), ('other', 'Other')], max_length=30)),
                ('previous_status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('occupied', 'Occupied'), ('blocked', 'Blocked'), ('maintenance', 'Maintenance'), ('out_of_order', 'Out of Order')], max_length=30)),
                ('new_status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('occupied', 'Occupied'), ('blocked', 'Blocked'), ('maintenance', 'Maintenance'), ('out_of_order', 'Out of Order')], max_length=30)),
                ('previous_available_count', models.PositiveIntegerField()),
                ('new_available_count', models.PositiveIntegerField()),
                ('reason', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('reference_id', models.CharField(blank=True, help_text='Booking ID / OTA ID / Ticket ID / External Reference', max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('adjusted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_adjustments', to=settings.AUTH_USER_MODEL)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='inventory.inventorycalendar')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['inventory'], name='idx_adjustment_inventory'), models.Index(fields=['adjustment_type'], name='idx_adjustment_type'), models.Index(fields=['created_at'], name='idx_adjustment_created')],
            },
        ),
    ]
