# Generated by Django 4.2.30 on 2026-08-06 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_room_room_uq_room_property_number_and_more'),
        ('inventory', '0003_inventoryadjustment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('rule_type', models.CharField(choices=[('property', 'Property'), ('room_type', 'Room Type'), ('room', 'Room')], default='property', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('minimum_stay', models.PositiveSmallIntegerField(default=1)),
                ('maximum_stay', models.PositiveSmallIntegerField(default=30)),
                ('booking_window_min_days', models.PositiveIntegerField(default=0)),
                ('booking_window_max_days', models.PositiveIntegerField(default=365)),
                ('closed_to_arrival', models.BooleanField(default=False)),
                ('closed_to_departure', models.BooleanField(default=False)),
                ('allowed_weekdays', models.JSONField(blank=True, default=list, help_text="Example: ['mon','tue','wed']")),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_rules', to='booking.property')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availability_rules', to='booking.room')),
                ('room_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.roomtype')),
            ],
            options={
                'ordering': ['property', 'name'],
                'indexes': [models.Index(fields=['property', 'status'], name='idx_avail_prop_status'), models.Index(fields=['rule_type'], name='idx_avail_rule_type')],
            },
        ),
        migrations.AddConstraint(
            model_name='availabilityrule',
            constraint=models.UniqueConstraint(fields=('property', 'name'), name='uq_avail_rule_property_name'),
        ),
    ]
