# Generated by Django 4.2.30 on 2026-08-07 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0014_reservationstatushistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='HousekeepingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('task_type', models.CharField(choices=[('checkout_cleaning', 'Checkout Cleaning'), ('stayover_cleaning', 'Stay-over Cleaning'), ('deep_cleaning', 'Deep Cleaning'), ('inspection', 'Inspection'), ('linen_change', 'Linen Change'), ('turndown', 'Turndown Service'), ('sanitization', 'Sanitization'), ('emergency', 'Emergency Cleaning')], max_length=40)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('scheduled_date', models.DateField()),
                ('estimated_duration_minutes', models.PositiveIntegerField(default=30)),
                ('instructions', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='housekeeping_tasks', to='booking.property')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='housekeeping_tasks', to='booking.room')),
            ],
            options={
                'ordering': ['scheduled_date', 'priority'],
                'indexes': [models.Index(fields=['property', 'scheduled_date'], name='idx_hk_property_date'), models.Index(fields=['room', 'status'], name='idx_hk_room_status'), models.Index(fields=['priority', 'status'], name='idx_hk_priority_status')],
            },
        ),
        migrations.AddConstraint(
            model_name='housekeepingtask',
            constraint=models.UniqueConstraint(fields=('room', 'scheduled_date', 'task_type'), name='uq_housekeeping_room_task_date'),
        ),
    ]
