# Generated by Django 4.2.30 on 2026-08-07 03:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('housekeeping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HousekeepingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment_status', models.CharField(choices=[('assigned', 'Assigned'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('reassigned', 'Reassigned')], default='assigned', max_length=20)),
                ('planned_start', models.DateTimeField(blank=True, null=True)),
                ('planned_end', models.DateTimeField(blank=True, null=True)),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('completion_percentage', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='housekeeping_assignments_created', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='housekeeping_assignments', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='housekeeping.housekeepingtask')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['assigned_to', 'assignment_status'], name='idx_hk_assign_user_status'), models.Index(fields=['task', 'assignment_status'], name='idx_hk_assign_task_status')],
            },
        ),
        migrations.AddConstraint(
            model_name='housekeepingassignment',
            constraint=models.UniqueConstraint(fields=('task', 'assigned_to'), name='uq_housekeeping_task_assignment'),
        ),
    ]
