# Generated by Django 4.2.30 on 2026-08-07 04:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('housekeeping', '0002_housekeepingassignment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HousekeepingStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previous_status', models.CharField(blank=True, choices=[('assigned', 'Assigned'), ('accepted', 'Accepted'), ('started', 'Started'), ('paused', 'Paused'), ('resumed', 'Resumed'), ('completed', 'Completed'), ('failed_inspection', 'Failed Inspection'), ('reopened', 'Reopened'), ('cancelled', 'Cancelled')], max_length=30)),
                ('new_status', models.CharField(choices=[('assigned', 'Assigned'), ('accepted', 'Accepted'), ('started', 'Started'), ('paused', 'Paused'), ('resumed', 'Resumed'), ('completed', 'Completed'), ('failed_inspection', 'Failed Inspection'), ('reopened', 'Reopened'), ('cancelled', 'Cancelled')], max_length=30)),
                ('change_source', models.CharField(choices=[('user', 'User'), ('system', 'System'), ('automation', 'Automation'), ('inspection', 'Inspection')], default='user', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='housekeepingassignment',
            name='uq_housekeeping_task_assignment',
        ),
        migrations.AddConstraint(
            model_name='housekeepingassignment',
            constraint=models.UniqueConstraint(fields=('task', 'assigned_to'), name='uq_housekeeping_task_assign'),
        ),
        migrations.AddField(
            model_name='housekeepingstatuslog',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='housekeeping.housekeepingassignment'),
        ),
        migrations.AddField(
            model_name='housekeepingstatuslog',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='housekeeping_status_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='housekeepingstatuslog',
            index=models.Index(fields=['assignment', 'created_at'], name='idx_hk_status_assignment_date'),
        ),
        migrations.AddIndex(
            model_name='housekeepingstatuslog',
            index=models.Index(fields=['new_status'], name='idx_hk_status_new'),
        ),
        migrations.AddIndex(
            model_name='housekeepingstatuslog',
            index=models.Index(fields=['change_source'], name='idx_hk_status_source'),
        ),
    ]
