# Generated by Django 4.2.30 on 2026-08-07 04:37

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_reservationstatushistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('housekeeping', '0003_housekeepingstatuslog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('electrical', 'Electrical'), ('plumbing', 'Plumbing'), ('hvac', 'HVAC / Air Conditioning'), ('civil', 'Civil'), ('painting', 'Painting'), ('furniture', 'Furniture'), ('appliance', 'Appliance'), ('it', 'IT / Network'), ('landscaping', 'Landscaping'), ('safety', 'Safety'), ('other', 'Other')], max_length=30)),
                ('request_type', models.CharField(choices=[('preventive', 'Preventive'), ('corrective', 'Corrective'), ('emergency', 'Emergency'), ('inspection', 'Inspection')], default='corrective', max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], default='normal', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('estimated_duration_minutes', models.PositiveIntegerField(default=60)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_requests_approved', to=settings.AUTH_USER_MODEL)),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_requests', to='booking.building')),
                ('floor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_requests', to='booking.floor')),
                ('housekeeping_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_requests', to='housekeeping.housekeepingtask')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='booking.property')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_requests_reported', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_requests', to='booking.room')),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
                'indexes': [models.Index(fields=['property', 'status'], name='idx_maint_property_status'), models.Index(fields=['room', 'status'], name='idx_maint_room_status'), models.Index(fields=['priority', 'status'], name='idx_maint_priority_status')],
            },
        ),
        migrations.AddConstraint(
            model_name='maintenancerequest',
            constraint=models.UniqueConstraint(fields=('property', 'title', 'created_at'), name='uq_maintenance_request_unique'),
        ),
    ]
