# Generated by Django 4.2.30 on 2026-08-07 04:39

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('housekeeping', '0004_maintenancerequest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_status', models.CharField(choices=[('started', 'Started'), ('in_progress', 'In Progress'), ('paused', 'Paused'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='started', max_length=20)),
                ('work_started_at', models.DateTimeField(blank=True, null=True)),
                ('work_completed_at', models.DateTimeField(blank=True, null=True)),
                ('labor_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('materials_used', models.JSONField(blank=True, default=list, help_text='List of parts/materials used.')),
                ('labor_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('material_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('before_notes', models.TextField(blank=True)),
                ('work_performed', models.TextField(blank=True)),
                ('after_notes', models.TextField(blank=True)),
                ('completion_evidence', models.JSONField(blank=True, default=dict, help_text='References to photos, videos, documents, invoices, etc.')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='housekeeping.maintenancerequest')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['request', 'created_at'], name='idx_maint_log_request_date'), models.Index(fields=['technician', 'work_status'], name='idx_maint_log_tech_status')],
            },
        ),
    ]
