# Generated by Django 4.2.30 on 2026-08-07 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_reservationstatushistory'),
        ('housekeeping', '0005_maintenancelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('checklist_type', models.CharField(choices=[('room_cleaning', 'Room Cleaning'), ('checkout', 'Checkout Cleaning'), ('deep_cleaning', 'Deep Cleaning'), ('public_area', 'Public Area'), ('restaurant', 'Restaurant'), ('event', 'Event Cleanup'), ('other', 'Other')], default='room_cleaning', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive')], default='draft', max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_checklists', to='booking.property')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['property', 'status'], name='idx_cleaning_checklist_status'), models.Index(fields=['property', 'checklist_type'], name='idx_cleaning_checklist_type')],
            },
        ),
        migrations.AddConstraint(
            model_name='cleaningchecklist',
            constraint=models.UniqueConstraint(fields=('property', 'slug', 'version'), name='uq_cleaning_checklist_property_version'),
        ),
    ]
