# Generated by Django 4.2.30 on 2026-08-07 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeping', '0006_cleaningchecklist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True, help_text='Detailed instructions for housekeeping staff.')),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('department', models.CharField(choices=[('housekeeping', 'Housekeeping'), ('laundry', 'Laundry'), ('maintenance', 'Maintenance'), ('front_office', 'Front Office'), ('security', 'Security'), ('other', 'Other')], default='housekeeping', max_length=30)),
                ('estimated_duration_minutes', models.PositiveIntegerField(default=5)),
                ('validation_rules', models.JSONField(blank=True, default=dict, help_text='Rules for completion validation.')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='housekeeping.cleaningchecklist')),
            ],
            options={
                'ordering': ['sequence'],
                'indexes': [models.Index(fields=['checklist', 'sequence'], name='idx_cleaning_item_order'), models.Index(fields=['department'], name='idx_cleaning_item_department')],
            },
        ),
        migrations.AddConstraint(
            model_name='cleaningchecklistitem',
            constraint=models.UniqueConstraint(fields=('checklist', 'sequence'), name='uq_cleaning_item_checklist_sequence'),
        ),
        migrations.AddConstraint(
            model_name='cleaningchecklistitem',
            constraint=models.UniqueConstraint(fields=('checklist', 'name'), name='uq_cleaning_item_checklist_name'),
        ),
    ]
