# Generated by Django 4.2.30 on 2026-08-07 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeping', '0008_inspection'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('passed', 'Passed'), ('failed', 'Failed'), ('not_applicable', 'Not Applicable')], default='pending', max_length=30)),
                ('passed', models.BooleanField(default=False)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('score', models.PositiveSmallIntegerField(default=0, help_text='Score awarded for this checkpoint.')),
                ('max_score', models.PositiveSmallIntegerField(default=10)),
                ('requires_corrective_action', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('checklist_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_items', to='housekeeping.cleaningchecklistitem')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='housekeeping.inspection')),
            ],
            options={
                'ordering': ['sequence'],
                'indexes': [models.Index(fields=['inspection', 'status'], name='idx_inspection_item_status'), models.Index(fields=['requires_corrective_action'], name='idx_inspection_item_corrective')],
            },
        ),
        migrations.AddConstraint(
            model_name='inspectionitem',
            constraint=models.UniqueConstraint(fields=('inspection', 'sequence'), name='uq_inspection_item_sequence'),
        ),
        migrations.AddConstraint(
            model_name='inspectionitem',
            constraint=models.UniqueConstraint(fields=('inspection', 'checklist_item'), name='uq_inspection_item_checklist'),
        ),
    ]
