# Generated by Django 4.2.30 on 2026-08-07 08:15

import apps.operations.housekeeping.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0004_mediareference_and_more'),
        ('booking', '0014_reservationstatushistory'),
        ('housekeeping', '0009_inspectionitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LostAndFound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('clothing', 'Clothing'), ('jewellery', 'Jewellery'), ('document', 'Document'), ('cash', 'Cash'), ('bag', 'Bag'), ('toiletry', 'Toiletry'), ('medicine', 'Medicine'), ('other', 'Other')], default='other', max_length=30)),
                ('item_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('location_found', models.CharField(max_length=200)),
                ('storage_location', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('found', 'Found'), ('stored', 'Stored'), ('guest_contacted', 'Guest Contacted'), ('claimed', 'Claimed'), ('returned', 'Returned'), ('donated', 'Donated'), ('disposed', 'Disposed')], default='found', max_length=30)),
                ('found_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('retention_until', models.DateField(default=apps.operations.housekeeping.models.default_retention_date)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_items', to='booking.guest')),
                ('found_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_found', to=settings.AUTH_USER_MODEL)),
                ('media_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lost_found_items', to='assets.mediareference')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_and_found_items', to='booking.property')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lost_and_found_items', to='booking.reservation')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lost_and_found_items', to='booking.room')),
            ],
            options={
                'ordering': ['-found_at'],
                'indexes': [models.Index(fields=['property', 'status'], name='idx_lost_found_property_status'), models.Index(fields=['room', 'status'], name='idx_lost_found_room_status'), models.Index(fields=['found_at'], name='idx_lost_found_date')],
            },
        ),
    ]
