# Generated by Django 4.2.30 on 2026-08-03 03:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text='Internal field name', max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=120)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('email', 'Email'), ('phone', 'Phone'), ('number', 'Number'), ('decimal', 'Decimal'), ('date', 'Date'), ('time', 'Time'), ('datetime', 'Date & Time'), ('password', 'Password'), ('url', 'URL'), ('file', 'File Upload'), ('image', 'Image Upload'), ('select', 'Select'), ('multiselect', 'Multi Select'), ('radio', 'Radio'), ('checkbox', 'Checkbox'), ('boolean', 'Boolean'), ('hidden', 'Hidden')], default='text', max_length=30)),
                ('placeholder', models.CharField(blank=True, max_length=255)),
                ('help_text', models.TextField(blank=True)),
                ('default_value', models.TextField(blank=True)),
                ('is_required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_readonly', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('validation_rules', models.JSONField(blank=True, default=dict, help_text='Validation rules such as min/max, regex, length, etc.')),
                ('ui_schema', models.JSONField(blank=True, default=dict, help_text='Frontend rendering hints.')),
                ('choices', models.JSONField(blank=True, default=list, help_text='Options for Select, Radio, Checkbox etc.')),
                ('conditional_logic', models.JSONField(blank=True, default=dict, help_text='Visibility conditions.')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='forms.form')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_order', 'id'],
                'indexes': [models.Index(fields=['form', 'display_order'], name='idx_formfield_order'), models.Index(fields=['form', 'field_type'], name='idx_formfield_type')],
            },
        ),
        migrations.AddConstraint(
            model_name='formfield',
            constraint=models.UniqueConstraint(fields=('form', 'slug'), name='uq_formfield_form_slug'),
        ),
        migrations.AddConstraint(
            model_name='formfield',
            constraint=models.UniqueConstraint(fields=('form', 'name'), name='uq_formfield_form_name'),
        ),
    ]
