# Generated by Django 4.2.17 on 2026-08-03 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0004_mediareference_and_more'),
        ('forms', '0003_formsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormSubmissionValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('value', models.TextField(blank=True, help_text='Primary value storage.')),
                ('json_value', models.JSONField(blank=True, default=dict, help_text='Structured values for complex field types.')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_values', to='forms.formfield')),
                ('media_reference', models.ForeignKey(blank=True, help_text='Uploaded file/image reference.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_submission_values', to='assets.mediareference')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='forms.formsubmission')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['field__display_order', 'id'],
                'indexes': [models.Index(fields=['submission'], name='idx_submissionvalue_submission'), models.Index(fields=['field'], name='idx_submissionvalue_field')],
            },
        ),
        migrations.AddConstraint(
            model_name='formsubmissionvalue',
            constraint=models.UniqueConstraint(fields=('submission', 'field'), name='uq_submission_field'),
        ),
    ]
