# Generated by Django 4.2.17 on 2026-08-03 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0004_formsubmissionvalue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('action_type', models.CharField(choices=[('email', 'Email'), ('notification', 'Notification'), ('crm', 'CRM Lead'), ('webhook', 'Webhook'), ('automation', 'Automation Workflow'), ('ai', 'AI Processing'), ('redirect', 'Redirect'), ('custom', 'Custom')], max_length=30)),
                ('trigger_event', models.CharField(choices=[('on_submit', 'On Submit'), ('on_approval', 'On Approval'), ('on_rejection', 'On Rejection')], default='on_submit', max_length=30)),
                ('execution_order', models.PositiveIntegerField(default=1, help_text='Lower numbers execute first.')),
                ('is_active', models.BooleanField(default=True)),
                ('configuration', models.JSONField(blank=True, default=dict, help_text='Action-specific configuration.')),
                ('conditions', models.JSONField(blank=True, default=dict, help_text='Optional execution conditions.')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='forms.form')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('execution_order', 'id'),
                'indexes': [models.Index(fields=['form', 'is_active'], name='idx_formaction_form_active'), models.Index(fields=['action_type'], name='idx_formaction_type')],
            },
        ),
        migrations.AddConstraint(
            model_name='formaction',
            constraint=models.UniqueConstraint(fields=('form', 'name'), name='uq_form_action_name'),
        ),
    ]
