# Generated by Django 4.2.30 on 2026-07-28 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_tenantsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('licensing', '0002_licensekey'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('WEB', 'Web'), ('MOBILE', 'Mobile'), ('DESKTOP', 'Desktop'), ('SERVER', 'Server')], default='WEB', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('REVOKED', 'Revoked'), ('EXPIRED', 'Expired')], db_index=True, default='ACTIVE', max_length=20)),
                ('activated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_identifier', models.CharField(blank=True, help_text='Future device/server fingerprint.', max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional activation information.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('license_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activations', to='licensing.licensekey')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license_activations', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'License Activation',
                'verbose_name_plural': 'License Activations',
                'db_table': 'license_activations',
                'ordering': ['-activated_at'],
            },
        ),
    ]
