# Generated by Django 4.2.17 on 2026-07-27 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions', '0003_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionFeature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_enabled', models.BooleanField(db_index=True, default=True)),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Optional usage limit. Null means unlimited.', null=True)),
                ('override_value', models.CharField(blank=True, help_text='Optional override for this feature.', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='subscriptions.feature')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='subscriptions.subscription')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subscription Feature',
                'verbose_name_plural': 'Subscription Features',
                'db_table': 'subscription_feature_mapping',
                'ordering': ['feature__category', 'feature__display_order'],
            },
        ),
        migrations.AddConstraint(
            model_name='subscriptionfeature',
            constraint=models.UniqueConstraint(fields=('subscription', 'feature'), name='uq_subscription_feature'),
        ),
    ]
