# Generated by Django 4.2.30 on 2026-07-28 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('code', models.SlugField(help_text='Unique internal configuration identifier.', max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('data_type', models.CharField(choices=[('STRING', 'String'), ('INTEGER', 'Integer'), ('DECIMAL', 'Decimal'), ('BOOLEAN', 'Boolean'), ('DATE', 'Date'), ('TIME', 'Time'), ('DATETIME', 'Date Time'), ('JSON', 'JSON'), ('EMAIL', 'Email'), ('URL', 'URL'), ('COLOR', 'Color')], db_index=True, default='STRING', max_length=20)),
                ('default_value', models.TextField(blank=True, help_text='Stored as text and interpreted according to data_type.')),
                ('is_required', models.BooleanField(default=False)),
                ('is_system', models.BooleanField(default=False, help_text='System keys cannot be deleted.')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='configuration_keys', to='configuration.configurationcategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuration Key',
                'verbose_name_plural': 'Configuration Keys',
                'db_table': 'configuration_keys',
                'ordering': ['category__display_order', 'display_order', 'name'],
            },
        ),
    ]
