# Generated by Django 4.2.30 on 2026-07-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_configurationkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationkey',
            name='ui_schema',
            field=models.JSONField(blank=True, default=dict, help_text='UI rendering metadata such as widget type, placeholder, help text, grouping, etc.'),
        ),
        migrations.AddField(
            model_name='configurationkey',
            name='validation_rules',
            field=models.JSONField(blank=True, default=dict, help_text='Validation metadata such as min/max, regex, allowed values, or length constraints.'),
        ),
    ]
