# Generated by Django 4.2.30 on 2026-07-28 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_tenantsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('configuration', '0003_configurationkey_ui_schema_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('value', models.TextField(blank=True, help_text='Stored as text. Parsed according to ConfigurationKey.data_type.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('configuration_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='configuration.configurationkey')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuration_values', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuration Value',
                'verbose_name_plural': 'Configuration Values',
                'db_table': 'configuration_values',
                'ordering': ['tenant', 'configuration_key'],
            },
        ),
        migrations.AddConstraint(
            model_name='configurationvalue',
            constraint=models.UniqueConstraint(fields=('tenant', 'configuration_key'), name='uq_configuration_value_tenant_key'),
        ),
    ]
