# Generated by Django 4.2.30 on 2026-07-28 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0002_websitetheme'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteMenu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('location', models.CharField(choices=[('HEADER', 'Header'), ('FOOTER', 'Footer'), ('MOBILE', 'Mobile'), ('SIDEBAR', 'Sidebar'), ('CUSTOM', 'Custom')], db_index=True, default='HEADER', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='website.website')),
            ],
            options={
                'db_table': 'website_menus',
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='websitemenu',
            constraint=models.UniqueConstraint(fields=('website', 'slug'), name='uq_website_menu_slug'),
        ),
    ]
