# Generated by Django 4.2.30 on 2026-08-06 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0008_room_room_uq_room_property_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=30)),
                ('description', models.TextField(blank=True)),
                ('rate_type', models.CharField(choices=[('standard', 'Standard'), ('corporate', 'Corporate'), ('package', 'Package'), ('ota', 'OTA'), ('member', 'Member'), ('promotional', 'Promotional')], default='standard', max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('is_refundable', models.BooleanField(default=True)),
                ('includes_breakfast', models.BooleanField(default=False)),
                ('minimum_advance_booking_days', models.PositiveIntegerField(default=0)),
                ('maximum_advance_booking_days', models.PositiveIntegerField(default=365)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_plans', to='booking.property')),
                ('room_types', models.ManyToManyField(blank=True, related_name='rate_plans', to='booking.roomtype')),
            ],
            options={
                'ordering': ['property', 'name'],
                'indexes': [models.Index(fields=['property', 'status'], name='idx_rateplan_property_status'), models.Index(fields=['property', 'rate_type'], name='idx_rateplan_property_type')],
            },
        ),
        migrations.AddConstraint(
            model_name='rateplan',
            constraint=models.UniqueConstraint(fields=('property', 'slug'), name='uq_rateplan_property_slug'),
        ),
        migrations.AddConstraint(
            model_name='rateplan',
            constraint=models.UniqueConstraint(fields=('property', 'name'), name='uq_rateplan_property_name'),
        ),
    ]
