# Generated by Django 4.2.30 on 2026-08-06 05:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_room_room_uq_room_property_number_and_more'),
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('rule_type', models.CharField(choices=[('percentage_discount', 'Percentage Discount'), ('percentage_surcharge', 'Percentage Surcharge'), ('fixed_discount', 'Fixed Discount'), ('fixed_surcharge', 'Fixed Surcharge'), ('occupancy', 'Occupancy Based'), ('length_of_stay', 'Length of Stay'), ('early_bird', 'Early Bird'), ('last_minute', 'Last Minute'), ('channel', 'Channel Specific'), ('custom', 'Custom')], max_length=40)),
                ('adjustment_value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('priority', models.PositiveIntegerField(default=100, help_text='Lower numbers execute first.')),
                ('stackable', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('minimum_nights', models.PositiveIntegerField(default=1)),
                ('maximum_nights', models.PositiveIntegerField(blank=True, null=True)),
                ('minimum_occupancy', models.PositiveIntegerField(default=1)),
                ('maximum_occupancy', models.PositiveIntegerField(blank=True, null=True)),
                ('booking_window_min_days', models.PositiveIntegerField(default=0)),
                ('booking_window_max_days', models.PositiveIntegerField(blank=True, null=True)),
                ('weekdays', models.JSONField(blank=True, default=list, help_text='Applicable weekdays (0=Monday ... 6=Sunday)')),
                ('channels', models.JSONField(blank=True, default=list, help_text='Applicable booking channels')),
                ('conditions', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_rules', to='booking.property')),
                ('rate_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='pricing.rateplan')),
            ],
            options={
                'ordering': ['priority', 'name'],
                'indexes': [models.Index(fields=['property', 'status'], name='idx_raterule_property_status'), models.Index(fields=['rate_plan', 'priority'], name='idx_raterule_priority'), models.Index(fields=['rule_type'], name='idx_raterule_type')],
            },
        ),
        migrations.AddConstraint(
            model_name='raterule',
            constraint=models.UniqueConstraint(fields=('rate_plan', 'slug'), name='uq_raterule_rateplan_slug'),
        ),
        migrations.AddConstraint(
            model_name='raterule',
            constraint=models.UniqueConstraint(fields=('rate_plan', 'name'), name='uq_raterule_rateplan_name'),
        ),
    ]
