# Generated by Django 4.2.30 on 2026-08-06 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_room_room_uq_room_property_number_and_more'),
        ('pricing', '0002_raterule_raterule_uq_raterule_rateplan_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('season_type', models.CharField(choices=[('peak', 'Peak Season'), ('off', 'Off Season'), ('holiday', 'Holiday Season'), ('festive', 'Festive Season'), ('monsoon', 'Monsoon Season'), ('weekend', 'Weekend Season'), ('custom', 'Custom Season')], default='custom', max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('priority', models.PositiveIntegerField(default=100, help_text='Lower value has higher priority.')),
                ('color_code', models.CharField(blank=True, help_text='UI calendar color reference.', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('recurring', models.BooleanField(default=False, help_text='Repeat every year.')),
                ('applicable_months', models.JSONField(blank=True, default=list)),
                ('conditions', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='booking.property')),
            ],
            options={
                'ordering': ['priority', 'start_date'],
                'indexes': [models.Index(fields=['property', 'status'], name='idx_season_property_status'), models.Index(fields=['property', 'start_date', 'end_date'], name='idx_season_date_range'), models.Index(fields=['season_type'], name='idx_season_type')],
            },
        ),
        migrations.AddConstraint(
            model_name='season',
            constraint=models.UniqueConstraint(fields=('property', 'slug'), name='uq_season_property_slug'),
        ),
        migrations.AddConstraint(
            model_name='season',
            constraint=models.UniqueConstraint(fields=('property', 'name'), name='uq_season_property_name'),
        ),
    ]
