# Generated by Django 4.2.30 on 2026-08-06 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_room_room_uq_room_property_number_and_more'),
        ('pricing', '0003_season_season_uq_season_property_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Original rate before adjustments', max_digits=10)),
                ('adjustment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('final_price', models.DecimalField(decimal_places=2, help_text='Final sell price', max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('minimum_stay', models.PositiveIntegerField(default=1)),
                ('maximum_stay', models.PositiveIntegerField(blank=True, null=True)),
                ('available_inventory', models.PositiveIntegerField(default=0)),
                ('occupancy_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('demand_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('channel', models.CharField(default='direct', max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('calculation_metadata', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_calendar', to='booking.property')),
                ('rate_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_calendar', to='pricing.rateplan')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_calendar', to='booking.roomtype')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_calendar', to='pricing.season')),
            ],
            options={
                'ordering': ['date'],
                'indexes': [models.Index(fields=['property', 'date'], name='idx_PC_property_date'), models.Index(fields=['room_type', 'date'], name='idx_PC_room_date'), models.Index(fields=['rate_plan', 'date'], name='idx_PC_rate_date')],
            },
        ),
        migrations.AddConstraint(
            model_name='pricecalendar',
            constraint=models.UniqueConstraint(fields=('room_type', 'rate_plan', 'date', 'channel'), name='uq_PC_room_rate_dt_channel'),
        ),
    ]
