# Generated by Django 4.2.30 on 2026-08-06 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_room_room_uq_room_property_number_and_more'),
        ('pricing', '0004_pricecalendar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DerivedRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('adjustment_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=30)),
                ('adjustment_value', models.DecimalField(decimal_places=2, help_text='Positive = markup, Negative = discount', max_digits=8)),
                ('channel', models.CharField(blank=True, help_text='Example: OTA, Direct, Mobile', max_length=50)),
                ('customer_segment', models.CharField(blank=True, help_text='Example: Corporate, Member', max_length=100)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('conditions', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('parent_rate_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derived_rates', to='pricing.rateplan')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derived_rates', to='booking.property')),
            ],
            options={
                'ordering': ['priority', 'name'],
                'indexes': [models.Index(fields=['property', 'status'], name='idx_derived_rate_prop_status'), models.Index(fields=['parent_rate_plan'], name='idx_derived_rate_parent_plan'), models.Index(fields=['channel'], name='idx_derived_rate_channel')],
            },
        ),
        migrations.AddConstraint(
            model_name='derivedrate',
            constraint=models.UniqueConstraint(fields=('property', 'slug'), name='uq_derived_rate_prop_slug'),
        ),
        migrations.AddConstraint(
            model_name='derivedrate',
            constraint=models.UniqueConstraint(fields=('parent_rate_plan', 'name'), name='uq_derived_rate_plan_name'),
        ),
    ]
