# Generated by Django 4.2.30 on 2026-07-28 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_alter_user_managers_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('code', models.SlugField(help_text='Example: booking.create', max_length=150, unique=True)),
                ('module', models.CharField(db_index=True, help_text='Module name (booking, website, pms, crm, etc.)', max_length=100)),
                ('scope', models.CharField(choices=[('PLATFORM', 'Platform'), ('TENANT', 'Tenant')], db_index=True, default='TENANT', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_system_permission', models.BooleanField(default=True, help_text='Core platform permission.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'permissions',
                'ordering': ['module', 'code'],
            },
        ),
    ]
