from django.db import models
from django.conf import settings
from apps.platform.tenants.models import Tenant
from apps.platform.common.models import BaseModel

class NotificationTemplate(BaseModel):
    """
    Reusable notification templates.
    """
    class Channel(models.TextChoices):
        EMAIL = "EMAIL", "Email"
        SMS = "SMS", "SMS"
        WHATSAPP = "WHATSAPP", "WhatsApp"
        PUSH = "PUSH", "Push"
        IN_APP = "IN_APP", "In-App"

    name = models.CharField(max_length=150, unique=True,)
    code = models.SlugField(max_length=150, unique=True, db_index=True,)
    channel = models.CharField(max_length=20, choices=Channel.choices, db_index=True,)
    subject = models.CharField(max_length=255, blank=True,)
    body = models.TextField()
    is_active = models.BooleanField(default=True,db_index=True,)

    class Meta:
        db_table = "notification_templates"
        ordering = ["name"]

    def __str__(self):
        return f"{self.name} ({self.channel})"


class Notification(BaseModel):
    """
    Runtime notification generated by the platform.
    """
    class Status(models.TextChoices):
        PENDING = "PENDING", "Pending"
        QUEUED = "QUEUED", "Queued"
        SENT = "SENT", "Sent"
        FAILED = "FAILED", "Failed"
        CANCELLED = "CANCELLED", "Cancelled"

    tenant = models.ForeignKey(Tenant, on_delete=models.CASCADE, related_name="notifications",)
    template = models.ForeignKey(NotificationTemplate, on_delete=models.PROTECT, related_name="notifications",)
    recipient = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True, related_name="notifications",)
    recipient_email = models.EmailField(blank=True,)
    recipient_phone = models.CharField(max_length=20, blank=True,)
    subject = models.CharField(max_length=255, blank=True,)
    body = models.TextField()
    status = models.CharField(max_length=20, choices=Status.choices, default=Status.PENDING, db_index=True,)
    scheduled_at = models.DateTimeField(null=True, blank=True,)
    sent_at = models.DateTimeField(null=True, blank=True,)

    class Meta:
        db_table = "notifications"
        ordering = ["-created_at"]

    def __str__(self):
        return f"{self.template.name} → {self.status}"


