# Generated by Django 4.2.30 on 2026-07-29 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0004_tenantsettings'),
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('asset_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('pdf', 'PDF'), ('svg', 'SVG'), ('other', 'Other')], max_length=20)),
                ('source_type', models.CharField(choices=[('upload', 'Upload'), ('youtube', 'YouTube'), ('instagram', 'Instagram'), ('vimeo', 'Vimeo'), ('facebook', 'Facebook'), ('url', 'URL')], default='upload', max_length=20)),
                ('storage_provider', models.CharField(choices=[('local', 'Local'), ('s3', 'Amazon S3'), ('cloudinary', 'Cloudinary'), ('azure', 'Azure Blob'), ('gcs', 'Google Cloud Storage'), ('external', 'External URL')], default='local', max_length=30)),
                ('file', models.FileField(blank=True, null=True, upload_to='assets/')),
                ('external_url', models.URLField(blank=True)),
                ('provider_asset_id', models.CharField(blank=True, max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('file_size', models.BigIntegerField(default=0)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Duration in seconds', null=True)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('caption', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('checksum', models.CharField(blank=True, max_length=128)),
                ('is_public', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='assets.mediafolder')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_assets', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['tenant', 'asset_type'], name='assets_medi_tenant__4a2794_idx'), models.Index(fields=['storage_provider'], name='assets_medi_storage_229569_idx'), models.Index(fields=['source_type'], name='assets_medi_source__74c296_idx')],
            },
        ),
    ]
