# Generated by Django 4.2.30 on 2026-07-29 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0002_mediaasset'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('variant_type', models.CharField(choices=[('original', 'Original'), ('thumbnail', 'Thumbnail'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('mobile', 'Mobile'), ('desktop', 'Desktop'), ('retina_2x', 'Retina 2x'), ('retina_3x', 'Retina 3x'), ('webp', 'WebP'), ('avif', 'AVIF'), ('watermark', 'Watermarked'), ('cropped', 'Cropped'), ('ai_enhanced', 'AI Enhanced'), ('custom', 'Custom')], max_length=30)),
                ('file', models.FileField(blank=True, null=True, upload_to='assets/variants/')),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('file_size', models.BigIntegerField(default=0)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('transformation', models.JSONField(blank=True, default=dict)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='assets.mediaasset')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='mediavariant',
            constraint=models.UniqueConstraint(fields=('asset', 'variant_type'), name='uq_media_variant_asset_type'),
        ),
    ]
