# Generated by Django 4.2.30 on 2026-07-30 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0003_mediavariant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('object_id', models.UUIDField()),
                ('reference_type', models.CharField(choices=[('primary', 'Primary'), ('gallery', 'Gallery'), ('logo', 'Logo'), ('favicon', 'Favicon'), ('hero', 'Hero'), ('background', 'Background'), ('icon', 'Icon'), ('thumbnail', 'Thumbnail'), ('attachment', 'Attachment'), ('video', 'Video'), ('document', 'Document'), ('other', 'Other')], default='primary', max_length=30)),
                ('order', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='assets.mediaasset')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='idx_media_reference_object')],
            },
        ),
        migrations.AddConstraint(
            model_name='mediareference',
            constraint=models.UniqueConstraint(fields=('asset', 'content_type', 'object_id', 'reference_type'), name='uq_media_reference_target_type'),
        ),
    ]
