# Generated by Django 4.2.30 on 2026-08-08 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_reservationstatushistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actual_check_out', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('checked_out', 'Checked Out'), ('late_checkout', 'Late Checkout'), ('early_checkout', 'Early Checkout')], default='pending', max_length=30)),
                ('inspection_status', models.CharField(choices=[('pending', 'Pending'), ('passed', 'Passed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('housekeeping_required', models.BooleanField(default=True)),
                ('room_ready_for_sale', models.BooleanField(default=False)),
                ('final_bill_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deposit_collected', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deposit_refunded', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('additional_charges', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('guest_feedback_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('guest_feedback', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('check_in', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='check_out', to='pms.checkin')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_check_outs', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_outs', to='booking.property')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pms_check_out', to='booking.reservation')),
            ],
            options={
                'ordering': ['-actual_check_out'],
                'indexes': [models.Index(fields=['property', 'status'], name='idx_checkout_property_status'), models.Index(fields=['actual_check_out'], name='idx_checkout_date')],
            },
        ),
        migrations.AddConstraint(
            model_name='checkout',
            constraint=models.UniqueConstraint(fields=('check_in',), name='uq_checkout_checkin'),
        ),
        migrations.AddConstraint(
            model_name='checkout',
            constraint=models.UniqueConstraint(fields=('reservation',), name='uq_checkout_reservation'),
        ),
    ]
