# Generated by Django 4.2.30 on 2026-08-08 03:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_reservationstatushistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pms', '0002_checkout_checkout_uq_checkout_checkin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('active', 'Active'), ('released', 'Released'), ('cancelled', 'Cancelled')], default='pending', max_length=30)),
                ('assignment_method', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic'), ('ai', 'AI Assisted')], default='manual', max_length=30)),
                ('change_type', models.CharField(choices=[('none', 'No Change'), ('upgrade', 'Upgrade'), ('downgrade', 'Downgrade'), ('room_change', 'Room Change')], default='none', max_length=30)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('effective_from', models.DateTimeField(blank=True, null=True)),
                ('effective_until', models.DateTimeField(blank=True, null=True)),
                ('assignment_reason', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_assignments_created', to=settings.AUTH_USER_MODEL)),
                ('reservation_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_assignments', to='booking.reservationroom')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='room_assignments', to='booking.room')),
            ],
            options={
                'ordering': ['-assigned_at', '-created_at'],
                'indexes': [models.Index(fields=['reservation_room', 'status'], name='idx_roomassign_resroom_status'), models.Index(fields=['room', 'status'], name='idx_roomassign_room_status'), models.Index(fields=['effective_from', 'effective_until'], name='idx_roomassign_effectiv_period')],
            },
        ),
    ]
