# Generated by Django 4.2.30 on 2026-08-08 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_reservationstatushistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pms', '0003_roomassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('initiated_by', models.CharField(choices=[('guest', 'Guest'), ('staff', 'Staff'), ('system', 'System'), ('ai', 'AI Assisted')], default='staff', max_length=20)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=20)),
                ('reason', models.CharField(choices=[('guest_request', 'Guest Request'), ('maintenance', 'Maintenance'), ('room_unavailable', 'Room Unavailable'), ('upgrade', 'Upgrade'), ('downgrade', 'Downgrade'), ('operational', 'Operational'), ('overbooking', 'Overbooking'), ('housekeeping', 'Housekeeping'), ('other', 'Other')], default='operational', max_length=30)),
                ('change_type', models.CharField(choices=[('same_category', 'Same Category'), ('upgrade', 'Upgrade'), ('downgrade', 'Downgrade')], default='same_category', max_length=30)),
                ('effective_at', models.DateTimeField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('authorized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_room_moves', to=settings.AUTH_USER_MODEL)),
                ('new_assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moves_to', to='pms.roomassignment')),
                ('new_room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='room_moves_to', to='booking.room')),
                ('previous_assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moves_from', to='pms.roomassignment')),
                ('previous_room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='room_moves_from', to='booking.room')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_moves', to='booking.reservation')),
                ('reservation_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_moves', to='booking.reservationroom')),
            ],
            options={
                'ordering': ['-effective_at', '-created_at'],
                'indexes': [models.Index(fields=['reservation', 'status'], name='idx_roommove_res_status'), models.Index(fields=['reservation_room', 'effective_at'], name='idx_roommove_resroom_date'), models.Index(fields=['previous_room', 'effective_at'], name='idx_roommove_prevroom_date'), models.Index(fields=['new_room', 'effective_at'], name='idx_roommove_newroom_date'), models.Index(fields=['status', 'effective_at'], name='idx_roommove_status_date')],
            },
        ),
    ]
