# Generated by Django 4.2.30 on 2026-08-08 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_mediareference_and_more'),
        ('booking', '0014_reservationstatushistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pms', '0004_roommove'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('passport', 'Passport'), ('aadhaar', 'Aadhaar'), ('pan', 'PAN'), ('driving_license', 'Driving License'), ('voter_id', 'Voter ID'), ('national_id', 'National ID'), ('other', 'Other')], max_length=30)),
                ('document_number', models.CharField(max_length=100)),
                ('issuing_country', models.CharField(blank=True, max_length=100)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='booking.guest')),
                ('media_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_documents', to='assets.mediareference')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_documents_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['guest', 'document_type'], name='idx_guestdoc_guest_type'), models.Index(fields=['guest', 'verification_status'], name='idx_guestdoc_guest_status'), models.Index(fields=['document_number'], name='idx_guestdoc_number'), models.Index(fields=['expiry_date'], name='idx_guestdoc_expiry')],
            },
        ),
        migrations.AddConstraint(
            model_name='guestdocument',
            constraint=models.UniqueConstraint(fields=('guest', 'document_type', 'document_number'), name='uq_guest_document_identity'),
        ),
    ]
