# Generated by Django 4.2.30 on 2026-08-08 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_reservationstatushistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pms', '0005_guestdocument_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credential_number', models.CharField(max_length=100, unique=True)),
                ('card_type', models.CharField(choices=[('physical', 'Physical Card'), ('rfid', 'RFID Card'), ('nfc', 'NFC Credential'), ('mobile', 'Mobile Key'), ('digital', 'Digital Credential'), ('other', 'Other')], default='physical', max_length=20)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('active', 'Active'), ('expired', 'Expired'), ('returned', 'Returned'), ('deactivated', 'Deactivated'), ('lost', 'Lost'), ('damaged', 'Damaged'), ('cancelled', 'Cancelled')], default='issued', max_length=20)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('check_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='key_cards', to='pms.checkin')),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='key_cards', to='booking.guest')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='key_cards_issued', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='key_cards', to='booking.reservation')),
                ('returned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='key_cards_returned', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='key_cards', to='booking.room')),
            ],
            options={
                'ordering': ['-issued_at', '-created_at'],
                'indexes': [models.Index(fields=['reservation', 'status'], name='idx_keycard_res_status'), models.Index(fields=['guest', 'status'], name='idx_keycard_guest_status'), models.Index(fields=['room', 'status'], name='idx_keycard_room_status'), models.Index(fields=['check_in'], name='idx_keycard_checkin'), models.Index(fields=['status', 'expires_at'], name='idx_keycard_status_expiry')],
            },
        ),
    ]
