# Generated by Django 4.2.30 on 2026-08-10 05:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0014_reservationstatushistory'),
        ('tenants', '0004_tenantsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Folio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folio_number', models.CharField(max_length=50)),
                ('folio_type', models.CharField(choices=[('guest', 'Guest Folio'), ('master', 'Master Folio'), ('company', 'Company Folio'), ('house', 'House Folio'), ('other', 'Other')], default='guest', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('closed', 'Closed'), ('void', 'Void')], default='open', max_length=30)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_folios', to=settings.AUTH_USER_MODEL)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='folios', to='booking.guest')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='folios', to='booking.property')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='folios', to='booking.reservation')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folios', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'property', 'status'], name='idx_folio_tenant_prop_status'), models.Index(fields=['reservation', 'status'], name='idx_folio_reservation_status'), models.Index(fields=['guest', 'status'], name='idx_folio_guest_status'), models.Index(fields=['property', 'folio_type'], name='idx_folio_property_type')],
            },
        ),
        migrations.AddConstraint(
            model_name='folio',
            constraint=models.UniqueConstraint(fields=('tenant', 'folio_number'), name='uq_folio_tenant_number'),
        ),
    ]
