# Generated by Django 4.2.30 on 2026-08-10 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_tenantsettings'),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_type', models.CharField(choices=[('room', 'Room Charge'), ('restaurant', 'Restaurant'), ('extra_bed', 'Extra Bed'), ('minibar', 'Minibar'), ('activity', 'Activity'), ('transfer', 'Transfer'), ('service', 'Service Fee'), ('laundry', 'Laundry'), ('spa', 'Spa'), ('event', 'Event'), ('other', 'Other')], default='other', max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('service_date', models.DateField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('posted', 'Posted'), ('void', 'Void'), ('pending', 'Pending')], default='posted', max_length=20)),
                ('source_type', models.CharField(blank=True, max_length=50)),
                ('source_reference', models.CharField(blank=True, max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('folio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.folio')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folio_items', to='tenants.tenant')),
            ],
            options={
                'ordering': ['service_date', 'sort_order', 'created_at'],
                'indexes': [models.Index(fields=['tenant', 'folio'], name='idx_folioitem_tenant_folio'), models.Index(fields=['folio', 'item_type'], name='idx_folioitem_folio_type'), models.Index(fields=['folio', 'service_date'], name='idx_folioitem_folio_date'), models.Index(fields=['tenant', 'status'], name='idx_folioitem_tenant_status')],
            },
        ),
    ]
