# Generated by Django 4.2.30 on 2026-08-10 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_tenantsettings'),
        ('billing', '0002_folioitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('charge_type', models.CharField(choices=[('room', 'Room Tariff'), ('restaurant', 'Restaurant'), ('extra_bed', 'Extra Bed'), ('minibar', 'Minibar'), ('laundry', 'Laundry'), ('spa', 'Spa'), ('transfer', 'Transfer'), ('service', 'Service Charge'), ('cancellation', 'Cancellation Fee'), ('early_checkin', 'Early Check-in'), ('late_checkout', 'Late Checkout'), ('activity', 'Activity'), ('event', 'Event'), ('other', 'Other')], default='other', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('default_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('unit', models.CharField(default='unit', max_length=30)),
                ('taxable', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='tenants.tenant')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['tenant', 'charge_type'], name='idx_charge_tenant_type'), models.Index(fields=['tenant', 'status'], name='idx_charge_tenant_status'), models.Index(fields=['tenant', 'active'], name='idx_charge_tenant_active'), models.Index(fields=['tenant', 'sort_order'], name='idx_charge_tenant_order')],
            },
        ),
        migrations.AddConstraint(
            model_name='charge',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='uq_charge_tenant_slug'),
        ),
        migrations.AddConstraint(
            model_name='charge',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='uq_charge_tenant_name'),
        ),
        migrations.AddConstraint(
            model_name='charge',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uq_charge_tenant_code'),
        ),
    ]
