# Generated by Django 4.2.30 on 2026-08-10 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_charge_charge_uq_charge_tenant_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tax_type', models.CharField(choices=[('gst', 'GST'), ('cgst', 'CGST'), ('sgst', 'SGST'), ('igst', 'IGST'), ('utgst', 'UTGST'), ('cess', 'Cess'), ('service_tax', 'Service Tax'), ('other', 'Other')], max_length=30)),
                ('tax_name', models.CharField(max_length=100)),
                ('tax_rate', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ('taxable_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('folio_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_lines', to='billing.folioitem')),
            ],
            options={
                'ordering': ['tax_type', 'tax_name'],
                'indexes': [models.Index(fields=['folio_item', 'tax_type'], name='idx_taxline_item_type'), models.Index(fields=['tax_name'], name='idx_taxline_tax_name')],
            },
        ),
        migrations.AddConstraint(
            model_name='taxline',
            constraint=models.UniqueConstraint(fields=('folio_item', 'tax_type', 'tax_name'), name='uq_taxline_item_type_name'),
        ),
    ]
