# Generated by Django 4.2.30 on 2026-08-10 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_taxline_taxline_uq_taxline_item_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount'), ('early_bird', 'Early Bird'), ('long_stay', 'Long Stay'), ('corporate', 'Corporate'), ('member', 'Member'), ('coupon', 'Coupon'), ('seasonal', 'Seasonal'), ('promotional', 'Promotional'), ('manual', 'Manual'), ('other', 'Other')], default='manual', max_length=30)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('discount_rate', models.DecimalField(blank=True, decimal_places=4, help_text='Percentage discount rate, if applicable.', max_digits=7, null=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('source_type', models.CharField(blank=True, max_length=50)),
                ('source_reference', models.CharField(blank=True, max_length=200)),
                ('reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('folio_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='billing.folioitem')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['folio_item', 'discount_type'], name='idx_discount_item_type'), models.Index(fields=['folio_item', 'name'], name='idx_discount_item_name')],
            },
        ),
    ]
