# Generated by Django 4.2.30 on 2026-08-10 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0005_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='FolioPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_type', models.CharField(choices=[('payment', 'Payment'), ('refund', 'Refund'), ('adjustment', 'Adjustment')], default='payment', max_length=20)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI'), ('bank_transfer', 'Bank Transfer'), ('online_gateway', 'Online Gateway'), ('cheque', 'Cheque'), ('other', 'Other')], default='cash', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded')], default='pending', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('payment_reference', models.CharField(blank=True, max_length=200)),
                ('gateway_name', models.CharField(blank=True, max_length=100)),
                ('gateway_order_id', models.CharField(blank=True, max_length=200)),
                ('gateway_transaction_id', models.CharField(blank=True, max_length=200)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('folio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.folio')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_folio_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['folio', 'status'], name='idx_foliopayment_folio_status'), models.Index(fields=['folio', 'payment_type'], name='idx_foliopayment_folio_type'), models.Index(fields=['payment_method'], name='idx_foliopayment_method'), models.Index(fields=['gateway_transaction_id'], name='idx_foliopayment_gateway_tx'), models.Index(fields=['paid_at'], name='idx_foliopayment_paid_at')],
            },
        ),
    ]
