# Generated by Django 4.2.30 on 2026-08-10 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0006_foliopayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='FolioAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adjustment_type', models.CharField(choices=[('credit', 'Manual Credit'), ('debit', 'Manual Debit'), ('rounding', 'Rounding Adjustment'), ('complimentary', 'Complimentary'), ('waiver', 'Waiver'), ('refund', 'Refund Adjustment'), ('correction', 'Correction'), ('write_off', 'Write-off'), ('cancellation', 'Cancellation Adjustment'), ('other', 'Other')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('posted', 'Posted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('reason', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('reference', models.CharField(blank=True, max_length=200)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_folio_adjustments', to=settings.AUTH_USER_MODEL)),
                ('folio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='billing.folio')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['folio', 'status'], name='idx_folioadj_folio_status'), models.Index(fields=['folio', 'adjustment_type'], name='idx_folioadj_folio_type'), models.Index(fields=['status'], name='idx_folioadj_status'), models.Index(fields=['approved_by'], name='idx_folioadj_approved_by'), models.Index(fields=['posted_at'], name='idx_folioadj_posted_at')],
            },
        ),
    ]
