# Generated by Django 4.2.30 on 2026-07-31 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0004_tenantsettings'),
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('template_type', models.CharField(choices=[('website', 'Website'), ('page', 'Page'), ('room', 'Room'), ('restaurant', 'Restaurant'), ('blog', 'Blog'), ('offer', 'Offer'), ('event', 'Event'), ('generic', 'Generic')], default='generic', max_length=30)),
                ('title_template', models.CharField(max_length=255)),
                ('description_template', models.TextField()),
                ('keyword_template', models.TextField(blank=True)),
                ('canonical_template', models.CharField(blank=True, max_length=500)),
                ('og_title_template', models.CharField(blank=True, max_length=255)),
                ('og_description_template', models.TextField(blank=True)),
                ('twitter_title_template', models.CharField(blank=True, max_length=255)),
                ('twitter_description_template', models.TextField(blank=True)),
                ('available_variables', models.JSONField(blank=True, default=list)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_templates', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['template_type', 'name'],
                'indexes': [models.Index(fields=['tenant', 'template_type'], name='idx_meta_template_type')],
            },
        ),
        migrations.AddConstraint(
            model_name='metatemplate',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='uq_meta_template_name'),
        ),
    ]
