# Generated by Django 4.2.30 on 2026-07-31 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_tenantsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seo', '0002_metatemplate_metatemplate_uq_meta_template_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('source_path', models.CharField(help_text='Old URL path (e.g. /rooms/deluxe-room/).', max_length=500)),
                ('destination_path', models.CharField(help_text='New URL or absolute URL.', max_length=500)),
                ('redirect_type', models.CharField(choices=[('301', '301 Permanent'), ('302', '302 Found'), ('307', '307 Temporary'), ('308', '308 Permanent')], default='301', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('preserve_query_string', models.BooleanField(default=True)),
                ('hit_count', models.PositiveBigIntegerField(default=0, editable=False)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redirects', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['source_path'],
                'indexes': [models.Index(fields=['tenant', 'source_path'], name='idx_redirect_lookup'), models.Index(fields=['is_active'], name='idx_redirect_active')],
            },
        ),
        migrations.AddConstraint(
            model_name='redirect',
            constraint=models.UniqueConstraint(fields=('tenant', 'source_path'), name='uq_redirect_source'),
        ),
    ]
