# Generated by Django 4.2.30 on 2026-07-31 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0004_tenantsettings'),
        ('seo', '0003_redirect_redirect_uq_redirect_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitemapConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('include_pages', models.BooleanField(default=True)),
                ('include_rooms', models.BooleanField(default=True)),
                ('include_restaurants', models.BooleanField(default=True)),
                ('include_blog_posts', models.BooleanField(default=True)),
                ('include_offers', models.BooleanField(default=True)),
                ('include_events', models.BooleanField(default=True)),
                ('include_gallery', models.BooleanField(default=True)),
                ('default_change_frequency', models.CharField(choices=[('always', 'Always'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('never', 'Never')], default='weekly', max_length=10)),
                ('default_priority', models.DecimalField(decimal_places=1, default=0.8, max_digits=2)),
                ('max_urls_per_file', models.PositiveIntegerField(default=50000)),
                ('ping_search_engines', models.BooleanField(default=True)),
                ('auto_regenerate', models.BooleanField(default=True)),
                ('last_generated_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sitemap_config', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['tenant'],
            },
        ),
    ]
