# Generated by Django 4.2.30 on 2026-07-31 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0004_sitemapconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemapconfig',
            name='excluded_paths',
            field=models.JSONField(blank=True, default=list, help_text='URL paths to exclude from sitemap generation.'),
        ),
    ]
