# Generated by Django 4.2.30 on 2026-08-01 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tenants', '0004_tenantsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seo', '0005_sitemapconfig_excluded_paths'),
    ]

    operations = [
        migrations.CreateModel(
            name='StructuredData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('schema_type', models.CharField(choices=[('website', 'Website'), ('webpage', 'WebPage'), ('organization', 'Organization'), ('local_business', 'LocalBusiness'), ('hotel', 'Hotel'), ('lodging_business', 'LodgingBusiness'), ('restaurant', 'Restaurant'), ('room', 'Room'), ('faq', 'FAQPage'), ('breadcrumb', 'BreadcrumbList'), ('event', 'Event'), ('review', 'Review'), ('offer', 'Offer'), ('product', 'Product'), ('article', 'Article'), ('blog_post', 'BlogPosting'), ('video', 'VideoObject'), ('image', 'ImageObject'), ('custom', 'Custom')], max_length=30)),
                ('object_id', models.UUIDField()),
                ('schema_json', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structured_data', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['schema_type', 'name'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='idx_structured_lookup'), models.Index(fields=['tenant', 'schema_type'], name='idx_structured_tenant_type')],
            },
        ),
        migrations.AddConstraint(
            model_name='structureddata',
            constraint=models.UniqueConstraint(fields=('content_type', 'object_id', 'schema_type'), name='uq_structured_data_object_schema'),
        ),
    ]
