# Generated by Django 4.2.17 on 2026-08-03 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyAmenity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150)),
                ('category', models.CharField(choices=[('general', 'General'), ('dining', 'Dining'), ('wellness', 'Wellness'), ('recreation', 'Recreation'), ('business', 'Business'), ('transport', 'Transport'), ('accessibility', 'Accessibility'), ('safety', 'Safety'), ('other', 'Other')], default='general', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Icon name (Font Awesome, Material Icons, etc.)', max_length=100)),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='booking.property')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('display_order', 'name'),
                'indexes': [models.Index(fields=['property', 'is_active'], name='idx_prop_amn_active'), models.Index(fields=['category'], name='idx_prop_amn_cat')],
            },
        ),
        migrations.AddConstraint(
            model_name='propertyamenity',
            constraint=models.UniqueConstraint(fields=('property', 'slug'), name='uq_property_amenity_slug'),
        ),
        migrations.AddConstraint(
            model_name='propertyamenity',
            constraint=models.UniqueConstraint(fields=('property', 'name'), name='uq_property_amenity_name'),
        ),
    ]
