# Generated by Django 4.2.17 on 2026-08-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_building_building_uq_building_property_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='building_type',
            field=models.CharField(choices=[('main', 'Main Building'), ('villa', 'Villa'), ('block', 'Block'), ('cottage', 'Cottage'), ('other', 'Other')], default='main', max_length=30),
        ),
    ]
