# Generated by Django 4.2.17 on 2026-08-03 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_building_building_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('floor_number', models.IntegerField(default=0, help_text='0 = Ground Floor')),
                ('floor_type', models.CharField(choices=[('basement', 'Basement'), ('ground', 'Ground Floor'), ('first', 'First Floor'), ('second', 'Second Floor'), ('third', 'Third Floor'), ('terrace', 'Terrace'), ('other', 'Other')], default='ground', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('under_maintenance', 'Under Maintenance'), ('closed', 'Closed')], default='active', max_length=30)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='booking.building')),
            ],
            options={
                'ordering': ['sort_order', 'floor_number', 'name'],
                'indexes': [models.Index(fields=['building', 'status'], name='idx_floor_building_status'), models.Index(fields=['building', 'sort_order'], name='idx_floor_building_order')],
            },
        ),
        migrations.AddConstraint(
            model_name='floor',
            constraint=models.UniqueConstraint(fields=('building', 'slug'), name='uq_floor_building_slug'),
        ),
        migrations.AddConstraint(
            model_name='floor',
            constraint=models.UniqueConstraint(fields=('building', 'floor_number'), name='uq_floor_building_number'),
        ),
    ]
