# Generated by Django 4.2.17 on 2026-08-03 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_floor_floor_uq_floor_building_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=30)),
                ('category', models.CharField(choices=[('standard', 'Standard'), ('deluxe', 'Deluxe'), ('premium', 'Premium'), ('suite', 'Suite'), ('villa', 'Villa'), ('family', 'Family'), ('dormitory', 'Dormitory'), ('other', 'Other')], default='standard', max_length=30)),
                ('short_description', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('base_occupancy', models.PositiveSmallIntegerField(default=2)),
                ('max_occupancy', models.PositiveSmallIntegerField(default=2)),
                ('max_adults', models.PositiveSmallIntegerField(default=2)),
                ('max_children', models.PositiveSmallIntegerField(default=0)),
                ('room_size', models.DecimalField(decimal_places=2, help_text='Area in square feet', max_digits=8)),
                ('bed_configuration', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('coming_soon', 'Coming Soon')], default='active', max_length=30)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to='booking.property')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['property', 'status'], name='idx_roomtype_property_status'), models.Index(fields=['property', 'category'], name='idx_roomtype_property_category')],
            },
        ),
        migrations.AddConstraint(
            model_name='roomtype',
            constraint=models.UniqueConstraint(fields=('property', 'slug'), name='uq_roomtype_property_slug'),
        ),
        migrations.AddConstraint(
            model_name='roomtype',
            constraint=models.UniqueConstraint(fields=('property', 'name'), name='uq_roomtype_property_name'),
        ),
    ]
