# Generated by Django 4.2.17 on 2026-08-03 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_roomtype_roomtype_uq_roomtype_property_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('category', models.CharField(choices=[('bedroom', 'Bedroom'), ('bathroom', 'Bathroom'), ('entertainment', 'Entertainment'), ('internet', 'Internet'), ('food_beverage', 'Food & Beverage'), ('comfort', 'Comfort'), ('safety', 'Safety'), ('accessibility', 'Accessibility'), ('outdoor', 'Outdoor'), ('other', 'Other')], default='comfort', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Bootstrap or FontAwesome icon', max_length=100)),
                ('is_featured', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='booking.roomtype')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['room_type', 'category'], name='idx_roomamenity_category'), models.Index(fields=['room_type', 'is_active'], name='idx_roomamenity_active')],
            },
        ),
        migrations.AddConstraint(
            model_name='roomamenity',
            constraint=models.UniqueConstraint(fields=('room_type', 'slug'), name='uq_roomamenity_roomtype_slug'),
        ),
        migrations.AddConstraint(
            model_name='roomamenity',
            constraint=models.UniqueConstraint(fields=('room_type', 'name'), name='uq_roomamenity_roomtype_name'),
        ),
    ]
