# Generated by Django 4.2.17 on 2026-08-03 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_roomamenity_roomamenity_uq_roomamenity_roomtype_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_number', models.CharField(max_length=30)),
                ('room_name', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('out_of_order', 'Out of Order'), ('maintenance', 'Maintenance'), ('blocked', 'Blocked'), ('inactive', 'Inactive')], default='available', max_length=30)),
                ('max_adults', models.PositiveSmallIntegerField(default=2)),
                ('max_children', models.PositiveSmallIntegerField(default=2)),
                ('is_smoking', models.BooleanField(default=False)),
                ('is_accessible', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='booking.building')),
                ('floor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='booking.floor')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='booking.property')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='booking.roomtype')),
            ],
            options={
                'ordering': ['sort_order', 'room_number'],
                'indexes': [models.Index(fields=['property', 'status'], name='idx_room_property_status'), models.Index(fields=['room_type', 'status'], name='idx_room_roomtype_status'), models.Index(fields=['building', 'floor'], name='idx_room_building_floor')],
            },
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('property', 'room_number'), name='uq_room_property_number'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('property', 'slug'), name='uq_room_property_slug'),
        ),
    ]
