# Generated by Django 4.2.30 on 2026-08-06 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_tenantsettings'),
        ('booking', '0008_room_room_uq_room_property_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('alternate_phone', models.CharField(blank=True, max_length=30)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('id_type', models.CharField(blank=True, max_length=50)),
                ('id_number', models.CharField(blank=True, max_length=100)),
                ('preferences', models.JSONField(blank=True, default=dict, help_text='Guest preferences and history')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('active', 'Active'), ('blocked', 'Blocked')], default='active', max_length=20)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='tenants.tenant')),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
                'indexes': [models.Index(fields=['tenant', 'phone'], name='idx_guest_tenant_phone'), models.Index(fields=['tenant', 'email'], name='idx_guest_tenant_email')],
            },
        ),
        migrations.AddConstraint(
            model_name='guest',
            constraint=models.UniqueConstraint(fields=('tenant', 'email'), name='uq_guest_tenant_email'),
        ),
    ]
