# Generated by Django 4.2.30 on 2026-08-06 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_tenantsettings'),
        ('booking', '0009_guest_guest_uq_guest_tenant_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_number', models.CharField(max_length=50, unique=True)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('adults', models.PositiveIntegerField(default=1)),
                ('children', models.PositiveIntegerField(default=0)),
                ('booking_source', models.CharField(choices=[('website', 'Website'), ('walk_in', 'Walk In'), ('phone', 'Phone'), ('ota', 'OTA'), ('corporate', 'Corporate'), ('agent', 'Travel Agent')], default='website', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='pending', max_length=30)),
                ('cancellation_status', models.CharField(choices=[('not_cancelled', 'Not Cancelled'), ('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_cancelled', max_length=30)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pricing_snapshot', models.JSONField(blank=True, default=dict, help_text='Frozen price details at booking time')),
                ('payment_summary', models.JSONField(blank=True, default=dict)),
                ('booking_metadata', models.JSONField(blank=True, default=dict)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='booking.guest')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='booking.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['property', 'check_in'], name='idx_reserv_prop_checkin'), models.Index(fields=['guest'], name='idx_reserv_guest'), models.Index(fields=['status'], name='idx_reserv_status')],
            },
        ),
    ]
