# Generated by Django 4.2.30 on 2026-08-06 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0005_derivedrate_derivedrate_uq_derived_rate_prop_slug_and_more'),
        ('booking', '0010_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rooms_count', models.PositiveIntegerField(default=1)),
                ('adults', models.PositiveIntegerField(default=1)),
                ('children', models.PositiveIntegerField(default=0)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('nightly_price_snapshot', models.JSONField(blank=True, default=dict, help_text='Frozen nightly pricing')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('final_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('assigned', 'Assigned'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('cancelled', 'Cancelled')], default='reserved', max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('rate_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservation_rooms', to='pricing.rateplan')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='booking.reservation')),
                ('room', models.ForeignKey(blank=True, help_text='Actual assigned physical room', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_rooms', to='booking.room')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservation_rooms', to='booking.roomtype')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['reservation'], name='idx_reserv_room_reservation'), models.Index(fields=['room', 'check_in', 'check_out'], name='idx_reserv_room_dates'), models.Index(fields=['room_type'], name='idx_reserv_room_type')],
            },
        ),
    ]
