# Generated by Django 4.2.30 on 2026-08-06 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_reservationroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('primary', 'Primary Guest'), ('adult', 'Adult'), ('child', 'Child'), ('infant', 'Infant')], default='adult', max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('identity_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('check_in_completed', models.BooleanField(default=False)),
                ('special_requests', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservation_history', to='booking.guest')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_guests', to='booking.reservation')),
                ('reservation_room', models.ForeignKey(blank=True, help_text='Assigned room within reservation.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='booking.reservationroom')),
            ],
            options={
                'ordering': ['reservation', '-is_primary', 'role', 'guest'],
                'indexes': [models.Index(fields=['reservation', 'role'], name='idx_res_guest_role'), models.Index(fields=['reservation_room'], name='idx_res_guest_room'), models.Index(fields=['guest'], name='idx_res_guest_guest')],
            },
        ),
        migrations.AddConstraint(
            model_name='reservationguest',
            constraint=models.UniqueConstraint(fields=('reservation', 'guest'), name='uq_reservation_guest'),
        ),
    ]
