# Generated by Django 4.2.30 on 2026-07-29 04:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0002_pagerevision_pagerevision_uq_page_revision_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('block_type', models.CharField(choices=[('HERO', 'Hero'), ('TEXT', 'Text'), ('GALLERY', 'Gallery'), ('IMAGE', 'Image'), ('VIDEO', 'Video'), ('CTA', 'Call To Action'), ('FAQ', 'FAQ'), ('TESTIMONIAL', 'Testimonial'), ('AMENITIES', 'Amenities'), ('ROOM_LIST', 'Room List'), ('CONTACT', 'Contact'), ('CUSTOM', 'Custom')], db_index=True, max_length=30)),
                ('identifier', models.SlugField(help_text='Unique block identifier within the page.', max_length=100)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('configuration', models.JSONField(blank=True, default=dict, help_text='Block configuration and content.')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_visible', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='cms.page')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'content_blocks',
                'ordering': ['display_order'],
            },
        ),
        migrations.AddConstraint(
            model_name='contentblock',
            constraint=models.UniqueConstraint(fields=('page', 'identifier'), name='uq_page_content_block_identifier'),
        ),
    ]
