# Generated by Django 4.2.30 on 2026-07-29 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0003_contentblock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.SlugField(help_text='Unique component code (e.g. hero, gallery, youtube-video)', max_length=100, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('layout', 'Layout'), ('content', 'Content'), ('media', 'Media'), ('booking', 'Booking'), ('marketing', 'Marketing'), ('social', 'Social'), ('integration', 'Integration'), ('utility', 'Utility')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('renderer', models.CharField(help_text='Renderer class identifier', max_length=150)),
                ('configuration_schema', models.JSONField(blank=True, default=dict)),
                ('default_configuration', models.JSONField(blank=True, default=dict)),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('is_system', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Component',
                'verbose_name_plural': 'Components',
                'ordering': ['category', 'name'],
            },
        ),
    ]
