# Generated by Django 4.2.30 on 2026-08-10 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTAProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(help_text='Stable internal provider code, e.g. booking-com.', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Human-readable provider name.', max_length=200, unique=True)),
                ('display_name', models.CharField(blank=True, help_text='Optional public/display name.', max_length=200)),
                ('provider_type', models.CharField(choices=[('ota', 'Online Travel Agency'), ('channel_manager', 'Channel Manager'), ('distribution_network', 'Distribution Network'), ('metasearch', 'Metasearch'), ('other', 'Other')], default='ota', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('api_supported', models.BooleanField(default=False)),
                ('webhook_supported', models.BooleanField(default=False)),
                ('reservation_sync_supported', models.BooleanField(default=False)),
                ('availability_sync_supported', models.BooleanField(default=False)),
                ('rate_sync_supported', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('deprecated', 'Deprecated')], default='active', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['status'], name='idx_ota_provider_status'), models.Index(fields=['provider_type', 'status'], name='idx_ota_provider_type_status'), models.Index(fields=['sort_order'], name='idx_ota_provider_order')],
            },
        ),
    ]
