# Generated by Django 4.2.30 on 2026-08-10 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_tenantsettings'),
        ('ota', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otaprovider',
            name='code',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='otaprovider',
            name='display_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='otaprovider',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name='OTAAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Internal name for this OTA account.', max_length=200)),
                ('account_reference', models.CharField(blank=True, help_text='External OTA account/property reference if available.', max_length=200)),
                ('account_email', models.EmailField(blank=True, max_length=254)),
                ('account_username', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('closed', 'Closed')], default='active', max_length=20)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='ota.otaprovider')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ota_accounts', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant', 'provider', 'name'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='idx_ota_acct_tenant_status'), models.Index(fields=['provider', 'status'], name='idx_ota_acct_provider_status'), models.Index(fields=['tenant', 'provider'], name='idx_ota_acct_tenant_provider')],
            },
        ),
        migrations.AddConstraint(
            model_name='otaaccount',
            constraint=models.UniqueConstraint(fields=('tenant', 'provider', 'name'), name='uq_ota_ac_tenant_provider_name'),
        ),
    ]
