# Generated by Django 4.2.30 on 2026-08-10 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ota', '0002_alter_otaprovider_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTAConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('connection_type', models.CharField(choices=[('api', 'API'), ('webhook', 'Webhook'), ('api_webhook', 'API + Webhook'), ('sftp', 'SFTP'), ('other', 'Other')], default='api', max_length=30)),
                ('environment', models.CharField(choices=[('production', 'Production'), ('sandbox', 'Sandbox'), ('test', 'Test')], default='production', max_length=30)),
                ('endpoint', models.URLField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('connecting', 'Connecting'), ('error', 'Error'), ('suspended', 'Suspended')], default='inactive', max_length=30)),
                ('sync_enabled', models.BooleanField(default=True)),
                ('sync_configuration', models.JSONField(blank=True, default=dict)),
                ('last_connected_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ota_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='ota.otaaccount')),
            ],
            options={
                'ordering': ['ota_account', 'name'],
                'indexes': [models.Index(fields=['ota_account', 'status'], name='idx_ota_conn_account_status'), models.Index(fields=['ota_account', 'environment'], name='idx_ota_conn_account_env'), models.Index(fields=['status'], name='idx_ota_conn_status')],
            },
        ),
        migrations.AddConstraint(
            model_name='otaconnection',
            constraint=models.UniqueConstraint(fields=('ota_account', 'name'), name='uq_ota_connection_account_name'),
        ),
    ]
